---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - assets:
      - path: artifacts/*/*
      - path: lenra-cli-docs/lenra-cli-docs.zip
        name: lenra-cli-docs-${nextRelease.gitTag}.zip
      - path: lenra-cli-docs/lenra-cli-docs.tar.gz
        name: lenra-cli-docs-${nextRelease.gitTag}.tar.gz
  - - "semantic-release-export-data"
