[package]
name = "lenra_cli"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "THe Lenra's command line interface"
readme = "../README.md"
repository = "https://github.com/lenra-io/lenra_cli"
keywords = ["cli", "lenra"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
edition = "2021"
name = "lenra"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.2"
log = "0.4.17"
env_logger = "0.9.0"
regex = "1.6.0"
lazy_static = "1.4.0"
dofigen = "1"
