[package]
name = "lenra_cli"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "The Lenra command line interface"
repository = "https://github.com/lenra-io/lenra_cli"
keywords = ["cli", "lenra"]
categories = ["command-line-utilities"]
include = [
    "**/*.rs",
    "Cargo.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
edition = "2021"
name = "lenra"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.2"
serde_json = "1.0"
log = "0.4.17"
env_logger = "0.9.0"
regex = "1.6.0"
lazy_static = "1.4.0"
dofigen = { git = "https://github.com/lenra-io/dofigen", branch = "expose-errors" }
docker-compose-types = "0.2.2"
open = "1"
rustyline = "10.0.0"
dirs = "4.0.0"
chrono = "0.4.22"
thiserror = "1.0.37"
colored = "2.0.0"
ureq = { version = "2.5.0", features = ["json"] }
tokio = { version = "1.23.0", features = ["full"] }
futures = "0.3.25"
async-trait = "0.1.60"
