name: Build doc CI
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./docs/page-builder
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run build